[tools]
node = "24"
bun = "1.3.10"
pnpm = "10"
npm = "latest"
opencode = "latest"

[settings.npm]
bun = true
package_manager = "bun"

[settings.status]
missing_tools = "if_other_versions_installed"

[settings]
paranoid = true
asdf_compat = true
gpg_verify = true
github_attestations = true
